# index.docker.io: wting/python2
from wting/base
maintainer William Ting <io@williamting.com>

# install packages
run apt-fast.sh install -y \
	make \
	curl \
	wget \
	git \
	python \
	python-dev \
	python-pip

run pip install --upgrade pip
